[package]
name = "purge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7.0"}
leafwing-input-manager = "0.3.0"
bevy_egui = "0.14"
bevy_config_cam = { version = "0.3.0"}