[package]
name = "purge_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
purge_common = { path = "../purge_common" }
bevy = { version = "0.7.0", features = ["dynamic"] }
